// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6VqWHvgZQkiIbGwdB_no8yX-7LjCe-ho',
    appId: '1:322693839084:web:fe9abfdecc266a92fa4dc9',
    messagingSenderId: '322693839084',
    projectId: 'registrationbackend-5cce7',
    authDomain: 'registrationbackend-5cce7.firebaseapp.com',
    storageBucket: 'registrationbackend-5cce7.firebasestorage.app',
    measurementId: 'G-G3MQKB7CPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRRKqykZzUcc_JX2yBOnX_nZ3xZcOH_qQ',
    appId: '1:322693839084:android:f0a461c4d8371611fa4dc9',
    messagingSenderId: '322693839084',
    projectId: 'registrationbackend-5cce7',
    storageBucket: 'registrationbackend-5cce7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbwaiNYJdkeIZ9eOSosITYIDv203kJiWM',
    appId: '1:322693839084:ios:19546f471d463701fa4dc9',
    messagingSenderId: '322693839084',
    projectId: 'registrationbackend-5cce7',
    storageBucket: 'registrationbackend-5cce7.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbwaiNYJdkeIZ9eOSosITYIDv203kJiWM',
    appId: '1:322693839084:ios:19546f471d463701fa4dc9',
    messagingSenderId: '322693839084',
    projectId: 'registrationbackend-5cce7',
    storageBucket: 'registrationbackend-5cce7.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6VqWHvgZQkiIbGwdB_no8yX-7LjCe-ho',
    appId: '1:322693839084:web:43359212cf378288fa4dc9',
    messagingSenderId: '322693839084',
    projectId: 'registrationbackend-5cce7',
    authDomain: 'registrationbackend-5cce7.firebaseapp.com',
    storageBucket: 'registrationbackend-5cce7.firebasestorage.app',
    measurementId: 'G-X8CT6WJRPW',
  );
}
